import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const DEMO_WHATSAPP='919999999999';
const ADMIN_PATH='/atelier-console-7x9q';
const ADMIN_PIN='VEA2026';
const fallback=[{id:1,name:'Mini Flower Set on Palm',price:299,category:'Flowers',image:'/images/product-01-mini-flower-set-on-palm.jpg',description:'Handcrafted mini flower set on palm made for gifting, celebrations and special moments.',video:'',instagram_link:'https://www.instagram.com/reel/VEA_01_demo/'}];
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
function useProducts(){const [products,setProducts]=useState([]);useEffect(()=>{const saved=localStorage.getItem('vea_products');if(saved){try{setProducts(JSON.parse(saved));return}catch{}}fetch('/products.json').then(r=>r.json()).then(setProducts).catch(()=>setProducts(fallback))},[]);const save=p=>{setProducts(p);localStorage.setItem('vea_products',JSON.stringify(p))};return [products,save]}
function App(){const path=window.location.pathname.replace(/\/$/,'');return path===ADMIN_PATH?<Admin/>:<Store/>}
function Header({cartCount,onCart}){return <header className="nav"><div className="nav-in"><a className="logo" href="#home"><span>V</span><b>VEA<small>CREATIONS</small></b></a><nav><a href="#collection">Collection</a><a href="#story">Our Story</a><a href="#reels">Reels</a></nav><button className="bag" onClick={onCart}>Bag <i>{cartCount}</i></button><a className="admin-secret" href={ADMIN_PATH} aria-label="admin">•</a></div></header>}
function Store(){const [products]=useProducts();const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('vea_cart')||'[]'));const [cat,setCat]=useState('All');const [selected,setSelected]=useState(null);const [cartOpen,setCartOpen]=useState(false);const [note,setNote]=useState('');const [hero,setHero]=useState(0);const timer=useRef();const categories=['All',...Array.from(new Set(products.map(p=>p.category)))];const filtered=useMemo(()=>cat==='All'?products:products.filter(p=>p.category===cat),[products,cat]);const heroItems=products.slice(0,8);const videos=products.filter(p=>p.video);
useEffect(()=>{localStorage.setItem('vea_cart',JSON.stringify(cart))},[cart]);useEffect(()=>{timer.current=setInterval(()=>setHero(h=>heroItems.length?(h+1)%heroItems.length:0),5000);return()=>clearInterval(timer.current)},[heroItems.length]);
const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0));const total=cart.reduce((s,i)=>s+i.price*i.qty,0);const count=cart.reduce((s,i)=>s+i.qty,0);
const checkout=()=>{if(!cart.length)return;const lines=['Hello VEA Creations 👋','','I would like to order:','',...cart.flatMap((i,n)=>[`${n+1}. ${i.name} — Qty: ${i.qty} — ${money(i.price*i.qty)}`,`Photo: ${location.origin}${i.image.startsWith('/')?i.image:'/'.concat(i.image)}`,`Instagram: ${i.instagram_link||'Not added'}`,'']),`Total: ${money(total)}`,...(note?['','My note: '+note]:[]),'','Please confirm availability, customization and delivery details. Thank you!'];const num=localStorage.getItem('vea_whatsapp')||DEMO_WHATSAPP;window.open(`https://wa.me/${num}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank')};
return <><Header cartCount={count} onCart={()=>setCartOpen(true)}/><main><section id="home" className="hero"><div className="hero-copy"><span className="eyebrow">HANDMADE · CURATED · PERSONAL</span><h1>Little pieces of<br/><em>something beautiful.</em></h1><p>Thoughtful flowers, keepsakes and gifts — made slowly, wrapped beautifully, and created for the moments that deserve more than ordinary.</p><div className="hero-actions"><a href="#collection" className="primary">Explore collection <b>↗</b></a><button className="linkbtn" onClick={()=>setCartOpen(true)}>View your bag <u>{count}</u></button></div><small className="signature">♡ Made with intention, for someone special.</small></div><div className="hero-stage">{heroItems.length>0&&<div className="hero-photo"><img src={heroItems[hero]?.image}/><div className="shade"/><div className="hero-meta"><small>0{hero+1} / 0{heroItems.length}</small><strong>{heroItems[hero]?.name}</strong></div><div className="hero-controls"><button onClick={()=>setHero((hero-1+heroItems.length)%heroItems.length)}>←</button><div>{heroItems.map((_,i)=><i key={i} className={i===hero?'on':''} onClick={()=>setHero(i)}/>)}</div><button onClick={()=>setHero((hero+1)%heroItems.length)}>→</button></div></div>}<div className="float-note">♡ <span><b>Made for moments</b><small>Birthday · Anniversary · Just because</small></span></div></div></section><div className="marquee">THE ART OF GIFTING　✦　HANDMADE WITH LOVE　✦　MADE TO BE REMEMBERED　✦　THE ART OF GIFTING</div>
<section id="collection" className="section"><div className="section-head"><div><span className="number">01</span><label>THE COLLECTION</label><h2>Choose a feeling.<br/><em>We'll make it tangible.</em></h2></div><p>Explore handcrafted pieces designed to turn ordinary moments into keepsakes.</p></div><div className="filters">{categories.map(c=><button key={c} className={c===cat?'active':''} onClick={()=>setCat(c)}>{c}</button>)}<span>{filtered.length} pieces</span></div><div className="grid">{filtered.map((p,i)=><ProductCard key={p.id} p={p} i={i} onOpen={()=>setSelected(p)} onAdd={()=>add(p)}/>)}</div></section>
<section id="story" className="story"><div className="story-art"><div className="orb"/><span>02</span><small>THE VEA JOURNAL</small></div><div className="story-copy"><label>WHY VEA</label><h2>Not just a gift.<br/><em>A little memory.</em></h2><p>We believe the most beautiful gifts aren't about how much they cost. They're about the feeling they carry. Every VEA piece is imagined, arranged and finished with small details that make it feel like it was made especially for you.</p><div className="points"><div><b>01</b><span>Thoughtfully handmade</span></div><div><b>02</b><span>Custom details welcome</span></div><div><b>03</b><span>Simple WhatsApp ordering</span></div></div></div></section>
<section id="reels" className="section dark"><div className="section-head"><div><span className="number">03</span><label>THE REELS</label><h2>See the little<br/><em>details.</em></h2></div><p>Tap any creation for a closer look. Each product can have its own Instagram Reel/Post link from the admin panel.</p></div><div className="reels">{videos.map(v=><button className="reel" key={v.id} onClick={()=>setSelected(v)}><video src={v.video} muted playsInline preload="metadata"/><span>▶</span><b>{v.name}</b></button>)}</div></section><section className="closing"><span>V</span><h2>For the little moments that<br/><em>mean everything.</em></h2><a href="#collection">Shop VEA ↗</a></section></main><footer><div className="logo"><span>V</span><b>VEA<small>CREATIONS</small></b></div><p>Handmade with intention.</p><small>© 2026 VEA Creations</small></footer>
{selected&&<ProductModal p={selected} onClose={()=>setSelected(null)} onAdd={()=>{add(selected);setSelected(null)}}/>}{cartOpen&&<Cart cart={cart} note={note} setNote={setNote} onClose={()=>setCartOpen(false)} change={change} total={total} checkout={checkout} setCart={setCart}/>}</>}
function ProductCard({p,i,onOpen,onAdd}){return <article className="card"><button className="card-img" onClick={onOpen}><img src={p.image}/><span className="num">{String(i+1).padStart(2,'0')}</span>{p.video&&<span className="reel-tag">REEL</span>}<div className="discover">DISCOVER ↗</div></button><div className="card-info"><div><small>{p.category}</small><h3>{p.name}</h3></div><b>{money(p.price)}</b></div><div className="card-actions"><a href={p.instagram_link||'#'} target="_blank" rel="noreferrer">Instagram ↗</a><button onClick={onAdd}>Add to bag +</button></div></article>}
function ProductModal({p,onClose,onAdd}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="x" onClick={onClose}>×</button><div className="modal-img"><img src={p.image}/></div><div className="modal-body"><label>{p.category}</label><h2>{p.name}</h2><strong>{money(p.price)}</strong><p>{p.description}</p>{p.video&&<video className="modal-video" controls src={p.video}/>}<a className="insta" href={p.instagram_link||'#'} target="_blank" rel="noreferrer">View Instagram Reel / Post ↗</a><button className="primary full" onClick={onAdd}>Add to bag — {money(p.price)}</button></div></div></div>}
function Cart({cart,note,setNote,onClose,change,total,setCart,checkout}){return <div className="cart-wrap"><div className="cart-back" onClick={onClose}/><aside className="cart"><div className="cart-head"><div><label>YOUR SELECTION</label><h3>Your bag <small>({cart.reduce((s,i)=>s+i.qty,0)})</small></h3></div><button onClick={onClose}>×</button></div><div className="cart-body">{!cart.length?<div className="empty">♡<h4>Your bag is empty.</h4><p>Something beautiful is waiting in the collection.</p></div>:<>{cart.map(i=><div className="line" key={i.id}><img src={i.image}/><div><small>{i.category}</small><h4>{i.name}</h4><b>{money(i.price)}</b><div className="qty"><button onClick={()=>change(i.id,-1)}>−</button><span>{i.qty}</span><button onClick={()=>change(i.id,1)}>+</button></div></div><button onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}>×</button></div>)}<div className="checkout"><div className="total"><span>Estimated total</span><b>{money(total)}</b></div><label>YOUR NOTE <small>OPTIONAL</small></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Colour preference, occasion or any little detail…"/><button className="whatsapp" onClick={checkout}>Continue on WhatsApp ↗</button><p>Your selected products, quantities, prices, photo links and Instagram links will be prepared in WhatsApp.</p></div></>}</div></aside></div>}
function Admin(){const [products,save]=useProducts();const [auth,setAuth]=useState(()=>sessionStorage.getItem('vea_admin')==='1');const [pin,setPin]=useState('');const [edit,setEdit]=useState(null);const [search,setSearch]=useState('');const [wa,setWa]=useState(localStorage.getItem('vea_whatsapp')||DEMO_WHATSAPP);const list=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||p.category.toLowerCase().includes(search.toLowerCase()));const empty={name:'',price:0,category:'Flowers',image:'/images/',description:'',video:'',instagram_link:'https://www.instagram.com/reel/DEMO_REPLACE_ME/'};
const login=e=>{e.preventDefault();if(pin===ADMIN_PIN){sessionStorage.setItem('vea_admin','1');setAuth(true)}else alert('Incorrect admin PIN')};if(!auth)return <div className="admin-login"><div className="login-card"><span>V</span><label>PRIVATE STUDIO</label><h1>VEA Admin</h1><p>Enter the studio PIN to manage the storefront.</p><form onSubmit={login}><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Admin PIN" autoFocus/><button className="primary full">Enter Studio</button></form><a href="/">← Back to store</a></div></div>;
const saveItem=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item=Object.fromEntries(f.entries());item.id=edit?.id||Date.now();item.price=Number(item.price||0);save(edit?products.map(p=>p.id===edit.id?item:p):[...products,item]);setEdit(null);e.currentTarget.reset()};const remove=id=>{if(confirm('Delete this product?'))save(products.filter(p=>p.id!==id))};const exportData=()=>{const blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vea-products.json';a.click()};const importData=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{save(JSON.parse(r.result));alert('Products imported')}catch{alert('Invalid JSON')}};r.readAsText(file)};
return <div className="admin"><header><a className="logo" href="/"><span>V</span><b>VEA<small>STUDIO</small></b></a><div><a href="/" target="_blank">View store ↗</a><button onClick={()=>{sessionStorage.removeItem('vea_admin');location.href=ADMIN_PATH}}>Lock</button></div></header><main><div className="admin-title"><div><label>PRIVATE STUDIO</label><h1>Store control.</h1><p>Manage products, pricing, images, videos and Instagram Reel/Post links. Changes are saved in this browser.</p></div><div className="admin-stats"><b>{products.length}</b><span>Products</span></div></div><div className="admin-toolbar"><input placeholder="Search products…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setEdit(empty)}>+ Add product</button><button onClick={exportData}>Export</button><label className="import">Import <input type="file" accept="application/json" onChange={importData}/></label></div><section className="settings"><label>WHATSAPP BUSINESS NUMBER</label><input value={wa} onChange={e=>setWa(e.target.value)} onBlur={()=>localStorage.setItem('vea_whatsapp',wa)} placeholder="919876543210"/><small>International format, no + or spaces. Saved only in this browser.</small></section><div className="admin-table">{list.map(p=><div className="admin-row" key={p.id}><img src={p.image}/><div><b>{p.name}</b><small>{p.category} · {money(p.price)}</small><a href={p.instagram_link} target="_blank" rel="noreferrer">{p.instagram_link||'No Instagram link'}</a></div><div className="row-actions"><button onClick={()=>setEdit(p)}>Edit</button><button onClick={()=>remove(p.id)}>Delete</button></div></div>)}</div></main>{edit&&<div className="overlay"><form className="editor" onSubmit={saveItem}><button type="button" className="x" onClick={()=>setEdit(null)}>×</button><label>PRODUCT EDITOR</label><h2>{edit.id?'Edit creation':'Add creation'}</h2><div className="form-grid"><input name="name" defaultValue={edit.name} placeholder="Product name" required/><input name="price" type="number" defaultValue={edit.price} placeholder="Price" required/><input name="category" defaultValue={edit.category} placeholder="Category" required/><input name="image" defaultValue={edit.image} placeholder="Image path / URL" required/><input name="video" defaultValue={edit.video} placeholder="Video path / URL (optional)"/><input name="instagram_link" defaultValue={edit.instagram_link} placeholder="Instagram Reel/Post URL" required/><textarea name="description" defaultValue={edit.description} placeholder="Description"/><button className="primary full">Save product</button></div></form></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);